name: component test

on:
  [pull_request, push]

  # workflow_run:
  #   workflows: ['Lint']
  #   types:
  #     - completed

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
